# version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: projectdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
